### ISSUE TITLE
`OrderInfo` struct has no `cost` field

### ISSUE THREAD

**Issue by gitmalong** [gmosx/kraken_sdk_rust#27]
* https://docs.rs/kraken_sdk_rest/0.19.0/kraken_sdk_rest/api/query_orders_info/struct.OrderInfo.html
* https://docs.kraken.com/rest/#tag/User-Data/operation/getOrdersInfo

**Comment by gmosx** [comment]
Thank you for reporting the various problems. I will have a look. (Of course PRs are also welcome ;-))

**Comment by gitmalong** [comment]
Thank you @gmosx !
