### ISSUE TITLE
`FeeSchedule(f64, f64)` fields are private

### ISSUE THREAD

**Issue by gitmalong** [gmosx/kraken_sdk_rust#30]
.. and can therefore not be read by library users :)

https://docs.rs/kraken_sdk_rest/0.19.0/kraken_sdk_rest/api/get_asset_pairs/struct.FeeSchedule.html

I would suggest to refactor the struct 

from

```rust
#[derive(Debug, Deserialize, Clone)]
pub struct FeeSchedule(f64, f64);
```

to

```rust
#[derive(Debug, Deserialize, Clone)]
pub struct FeeSchedule {
  pub volume: f64,
  pub percent_fee: f64
}
```

**Comment by gmosx** [comment]
I made the fields public, in a follow-up PR I may also implement the refactoring you suggested (or you can send a PR).
