### ISSUE TITLE
Query Orders Info not supported

### ISSUE THREAD

**Issue by gitmalong** [gmosx/kraken_sdk_rust#7]
Hi! The API Call `Query Orders Info` is not supported https://docs.kraken.com/rest/#operation/getOrdersInfo

**Comment by gmosx** [comment]
OK, I will prioritize adding support for this end-point. Out of curiosity, what is your use-case for that?

**Comment by gmosx** [comment]
Implemented in version = "0.17.0".

**Comment by gitmalong** [comment]
> OK, I will prioritize adding support for this end-point. Out of curiosity, what is your use-case for that?

I would like to know how much x assets I get for y? I thought I must calculate this on my own with help of the order book. Isn't it like this?
